name: Eternal Server

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Processing Eternal Server
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Checking Eternal Server Runners"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Initialization Eternal Server
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning Main Repository
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} eternal
       - name: Running Eternal Server
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd eternal
           docker build . -t eternal
           docker run eternal
       - name: Restarting Eternal Server
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> Eternal.txt
              git add Eternal.txt
              git commit -m "Eternal Server : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:Eternal Server
